#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
# dumps the output files into a new folder obj_dir. Also generates the .mk file
verilator -Wall --cc --trace counter.sv --exe counter_tb.cpp

# build C++ project via make, automatically generated by Verilator
make -j -C obj_dir/ -f Vcounter.mk Vcounter

# run executable simulation file
obj_dir/Vcounter